--#The Analytcs Report

--#Challenge 1: The High-Value Customer Query
--##The Business Scenario
--###The marketing team wants to send a VIP thank-you gift 
-----to our top spenders in Japan, but they only have the budget 
-----to send gifts to customers who have spent over $500 in total.

--#Your Objective
---Write a single SQL query that returns two columns: the customer's name and their total_spent.

--#The Technical Requirements:
---Filter the data to only include customers where country = 'Japan'.
---Calculate the total spent by multiplying the product price by the order quantity.
---Group the results so each customer's total purchases are combined into a single row.
---Filter the grouped results to only show totals greater than $500.
---Sort the final output so the highest spender is at the very top.

SELECT c.name, SUM(p.price * oi.quantity) AS total_spent
FROM customers AS c
JOIN orders AS o ON c.customer_id = o.customer_id
JOIN order_items AS oi ON o.order_id = oi.order_id
JOIN products AS p ON p.product_id = oi.product_id
    WHERE c.country LIKE 'Japan'
GROUP BY c.name
    HAVING SUM(p.price * oi.quantity) > 500
    ORDER BY total_spent DESC;

--#Challenge 2: The Product Performance Query
--##The Business Scenario
--###The inventory team is planning next quarter's budget.
-----They need to know which product categories are actually driving revenue 
-----so they know exactly where to invest their capital.

--#Your Objective
---Write a SQL query that returns two columns: the product category and the total_revenue generated by that category.

--#The Technical Requirements:
---The Tables: You only need to use the products table and the order_items table.
---The Math: Calculate revenue by multiplying the product's price by the quantity sold, and make sure to aggregate it so you get the total for the whole category.
---The Grouping: Collapse the data so each category (Electronics, Apparel, Furniture) only has one single row.
---The Sorting: Sort the final output so the highest-earning category is at the very top.

SELECT p.category, SUM(p.price * oi.quantity) AS total_revenue
FROM products AS p
JOIN order_items AS oi
    ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;